# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-27 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre_apellidos']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre_apellidos']},
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='nombre_apellidos',
        ),
    ]
