# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_auto_20210827_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='carnet',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
