# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-08-28 14:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_auto_20210827_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CI incorrecto', regex='^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='carnet',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CI incorrecto', regex='^[0-9]{2}(0[1-9]|1[0-2])(31|30|(0[1-9]|[1-2][0-9]))[0-9]{5}$')]),
        ),
    ]
